# Generated by Django 6.0.4 on 2026-04-20 12:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('checkpoint_path', models.CharField(blank=True, default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='MicroscopyImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='uploads/microscopy/')),
                ('treatment_group', models.CharField(blank=True, default='', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('num_channels', models.IntegerField(blank=True, null=True)),
                ('z_slices', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('puncta_count', models.IntegerField(blank=True, null=True)),
                ('puncta_density', models.FloatField(blank=True, null=True)),
                ('mip_image', models.ImageField(blank=True, upload_to='results/mip/')),
                ('segmentation_mask', models.ImageField(blank=True, upload_to='results/masks/')),
                ('overlay_image', models.ImageField(blank=True, upload_to='results/overlays/')),
                ('analysis_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='synapse_web.analysisrun')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='synapse_web.microscopyimage')),
            ],
        ),
    ]
