# Generated by Django 6.0.5 on 2026-05-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synapse_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysisrun',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='commit_sha',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='config_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='error_traceback',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='image_manifest',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='progress_message',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysisrun',
            name='error_message',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddConstraint(
            model_name='imageresult',
            constraint=models.UniqueConstraint(fields=('analysis_run', 'image'), name='uniq_result_per_run_image'),
        ),
    ]
