# Generated by Django 6.0.5 on 2026-05-21 09:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synapse_web', '0002_alter_analysisrun_options_analysisrun_commit_sha_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceImageStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_image', models.CharField(max_length=500)),
                ('treatment_group', models.CharField(blank=True, default='', max_length=255)),
                ('n_patches', models.PositiveIntegerField()),
                ('cluster_counts', models.JSONField(default=dict)),
                ('dominant_cluster', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['source_image'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='imageresult',
            name='uniq_result_per_run_image',
        ),
        migrations.RemoveField(
            model_name='analysisrun',
            name='image_manifest',
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='bundle_dir',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='clustering_summary',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='embedding_dim',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='input_dir',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='input_manifest',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='mean_ari',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='n_clusters',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='n_patches',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='n_source_images',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='output_dir',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='pca_dim',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='picked_resolution',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='run_kind',
            field=models.CharField(choices=[('extract_and_cluster', 'Extract embeddings + cluster'), ('cluster_only', 'Cluster only (pre-built bundle)')], default='extract_and_cluster', max_length=20),
        ),
        migrations.AddField(
            model_name='sourceimagestats',
            name='analysis_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_stats', to='synapse_web.analysisrun'),
        ),
        migrations.RemoveField(
            model_name='imageresult',
            name='analysis_run',
        ),
        migrations.RemoveField(
            model_name='imageresult',
            name='image',
        ),
        migrations.AddConstraint(
            model_name='sourceimagestats',
            constraint=models.UniqueConstraint(fields=('analysis_run', 'source_image'), name='uniq_sourcestat_per_run_image'),
        ),
        migrations.DeleteModel(
            name='ImageResult',
        ),
        migrations.DeleteModel(
            name='MicroscopyImage',
        ),
    ]
